{% set repo = "apache" %}
{% set name = "age" %}

package:
  repo: {{ repo }}
  name: {{ name }}
  pg_version: {{ pg_version }}
  version: {{ version }}

source:
  url: https://github.com/{{ repo }}/{{ name }}/releases/download/{{ pg_version }}%2Fv{{ version }}-rc0/{{ repo }}-{{ name }}-{{ version }}-src.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - perl            # [build_platform == target_platform]
    - gnuconfig       # [unix]
    - postgresql      # [build_platform != target_platform]
    - make            # [unix]
    - flex            # [unix]
    - bison           # [unix]
    - m2-patch        # [win]
    - m2-diffutils    # [win]
    - posix           # [win]
  host:
    - postgresql <17  # [win]
    - postgresql      # [not win]
  run:
    - {{ pin_compatible('libpq', max_pin='x.x.x') }}        # [win]
    - libpq                                                 # [not win]

test:
  commands:
    - test -f $PREFIX/lib/age.so                                                        # [linux]
    - test -f $PREFIX/lib/age.dylib                                                     # [osx]
    - test -f $PREFIX/share/extension/age--{{ version }}.sql                            # [unix]
    - test -f $PREFIX/share/extension/age.control                                       # [unix]
    - if not exist %LIBRARY_LIB%\age.dll exit 1                                         # [win]
    - if not exist %LIBRARY_PREFIX%\share\extension\age--{{ version }}.sql exit 1       # [win]
    - if not exist %LIBRARY_PREFIX%\share\extension\age.control exit 1                  # [win]


about:
  home: https://github.com/apache/age
  summary: Apache AGE - graph database extension for PostgreSQL.
  description: Apache AGE is a PostgreSQL extension that provides a graph database engine with support for property graphs and Cypher queries.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://age.apache.org/
  dev_url: https://github.com/apache/age

extra:
  recipe-maintainers:
    - lemonhead94
